// This file is generated by FlutterFire CLI.
// Run: flutterfire configure
// DO NOT edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMyRUp2FLCdi3-aRQOq02LamUZiR1hNTI',
    appId: '1:667532037931:web:c5334a767186e2cdc17f6e',
    messagingSenderId: '667532037931',
    projectId: 'cinewave-2be7d',
    authDomain: 'cinewave-2be7d.firebaseapp.com',
    storageBucket: 'cinewave-2be7d.firebasestorage.app',
  );

  // ⚠️  REPLACE these values after running: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByrz_bgV7suxq7gSEMxwAWWflIQIUGKto',
    appId: '1:667532037931:android:6cb21a0b7af38ba5c17f6e',
    messagingSenderId: '667532037931',
    projectId: 'cinewave-2be7d',
    storageBucket: 'cinewave-2be7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.cinewave',
  );
}